version: "3"
services:
  vue:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    command: ["npm", "run", "start-http-server"]
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue
      - laravel

  laravel:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: boncard
      DB_USERNAME: boncarduser
      DB_PASSWORD: passwd2341
    volumes:
      - ./backend:/var/www/

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: boncard
      MYSQL_USER: boncarduser
      MYSQL_PASSWORD: passwd2341
      MYSQL_ROOT_PASSWORD: rootpasswd2341
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
